services:
  # API service (Laravel)
  api:
    image: calvicii/onloc-api
    container_name: onloc-api
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=onloc
      - DB_USERNAME=onloc
      - DB_PASSWORD=onloc
    ports:
      - "8000:8000" # Expose Laravel API on port 8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # UI service (React)
  ui:
    image: calvicii/onloc-ui
    container_name: onloc-ui
    environment:
      - REACT_APP_API_URL=http://onloc-api:8000
    ports:
      - "3000:3000" # Expose React UI on port 3000
    depends_on:
      - api
    restart: unless-stopped

  # Nginx for proxying requests
  nginx:
    image: nginx:latest
    container_name: onloc-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "6144:6144" # Expose Nginx on port 6144
    depends_on:
      - api
      - ui
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: onloc-db
    environment:
      POSTGRES_DB: onloc
      POSTGRES_USER: onloc
      POSTGRES_PASSWORD: onloc
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onloc" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: onloc-network
